services:
  mytvs_svc:
    image: nodeapp1
    environment: 
      - NODE_PORT=4004
    ports:
      - 4004 
    networks:
      - tvs-net
    volumes:
      - mytvs-repo:/data
networks:
    tvs-net:


volumes:
    mytvs-repo:
